on: [push, pull_request]
name: Build benches on nightly toolchain
jobs:
  build_benchmarks:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
      - name: Build benchmarks
        run: cargo build --benches --all --verbose
