on: [push, pull_request]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
      - name: Build
        env:
          CARGO_UNSTABLE_SPARSE_REGISTRY: true
          RUSTFLAGS: "-D warnings"
        run: cargo build --all --verbose
      - name: Build for native CPU
        env:
          CARGO_UNSTABLE_SPARSE_REGISTRY: true
          RUSTFLAGS: "-C target-cpu=native -D warnings"
        run: cargo build --all --verbose
