on: [push, pull_request]
name: Lints on nightly toolchain
jobs:
  lints:
    strategy:
      fail-fast: false
      matrix:
        manifest_path:
          - "Cargo.toml"
          - "horcrux/Cargo.toml"
        rustflags:
          - "-D warnings"
          - "-C target-cpu=native -D warnings"
        features:
          - ""
          - "--all-features"
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy

      - name: Check Clippy lints
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}
        with:
          command: clippy
          args: --manifest-path ${{ matrix.manifest_path }} ${{ matrix.features }} --verbose
