on: [push, pull_request]
name: Lints on nightly toolchain
jobs:
  lints:
    strategy:
      fail-fast: false
      matrix:
        manifest_path:
          - "Cargo.toml"
          - "horcrux/Cargo.toml"
        rustflags:
          - "-D warnings"
          - "-C target-cpu=native -D warnings"
        features:
          - ""
          - "--all-features"
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Check Clippy lints
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}
        run: cargo clippy --manifest-path ${{ matrix.manifest_path }} ${{ matrix.features }} --verbose
